### ISSUE TITLE
Adding requirements.txt

### ISSUE THREAD

**Issue by JackHughes03** [ThiagoServulo/CoinRecognition#1]
Hey! I've been looking at starting my own project very similar to this one, but with a larger dataset of coins. I wanted to run this project and poke around a bit at how you did things. I have to say, i'm very impressed. Instructions are super clear and code is nearly formatted.

I've not created an issue before but so forgive me if this is pedantic. Only recommendation is to add in a requirements.txt so we can run it gracefully in an IDE.

Thank you!

**Comment by ThiagoServulo** [comment]
Hi! Thank you so much for your interest and positive feedback! I'm glad the instructions and code are clear. I’ve added the requirements.txt file to the project, and I am using Python version 3.9.10. Feel free to explore and if you have any questions or want to discuss anything, I’m here to help.
